// Soluzione completa usata dai test automatici.
// Passi:
//   ['use', target, verb?, opts?]      target = id hotspot | 'npc:<id>' | 'partner'
//   ['item', target, itemId, opts?]    usa un oggetto su un hotspot/personaggio
//   ['combine', a, b, opts?]           oggetto su oggetto
//   ['examine', itemId, opts?]
//   ['switch', 'beps'|'kiki']
//   ['expect', condizione]             condizione nel linguaggio del gioco
//   ['scene', sceneId]                 verifica la scena corrente
// opts: { topics: [...], choices: [...] }  temi da scegliere (id o {item}) e scelte (sottostringhe)

// FULL: tutto il contenuto opzionale, tutte le scelte "buone", finale perfetto.
export const FULL = [
  // ---------- CAPITOLO 1 ----------
  ['scene', 'c1_studio'],
  ['use', 'computer', null, { choices: ['NON_APRIRE'] }],
  ['use', 'macchinetta'],
  ['use', 'porta'],
  ['scene', 'c1_lungarno'],
  ['use', 'targa', 'look'],
  ['use', 'donna'],
  ['use', 'verso_cantiere'],
  ['scene', 'c1_cantiere'],
  ['use', 'npc:sandro', 'talk', { topics: ['caffe_dato', 'stanza', 'chi_murato', 'acqua'] }],
  ['item', 'armadio', 'coltellino'],
  ['use', 'crepa'],
  ['use', 'lira'],
  ['use', 'bolla'],
  ['use', 'gradini', 'look'],
  ['examine', 'frammenti'],
  ['expect', 'item.promemoria'],
  ['use', 'uscita'],
  ['use', 'porta_archivio'],
  ['scene', 'c1_archivio'],
  ['use', 'npc:kiki_lettrice', 'talk', { topics: ['contrario', 'orfeo'] }],
  ['use', 'npc:archivista', 'talk', { topics: [{ item: 'promemoria' }, 'orfeo', 'alluvione', 'donna'] }],
  ['expect', 'flag.catalogo_ok'],
  ['use', 'foto_alluvione'],
  ['use', 'schedario', null, { choices: ['Dipende', 'Andiamo'] }],
  ['expect', 'flag.met_kiki && item.scheda_o17'],
  ['use', 'porta_deposito'],
  ['scene', 'c1_corridoio'],
  ['use', 'registro'],
  ['use', 'ripiano'],
  ['expect', 'flag.blackout'],
  ['switch', 'kiki'],
  ['use', 'quadro'],
  ['expect', '!flag.blackout'],
  ['use', 'microcassetta'],
  ['switch', 'beps'],
  ['use', 'uscita'],
  ['use', 'uscita'],
  ['scene', 'c1_lungarno'],
  ['use', 'npc:varano_lamp', 'talk', { choices: ['Chi è lei'] }],
  ['use', 'porta_caffe'],
  ['scene', 'c1_caffe'],
  ['use', 'npc:tommaso', 'talk', { topics: ['cappuccino', 'donna', 'grigio'] }],
  ['use', 'quadro'],
  ['use', 'giornale', 'look'],
  ['item', 'laptop', 'usb', { choices: ['terzo gradino'] }],
  ['expect', 'flag.pdf_open'],
  ['use', 'partner', 'talk', { topics: ['c1_foto', 'c1_voce', 'c1_medaglione', 'c1_chi', 'c1_buio'], choices: ['Mi dispiace', 'In una crepa'] }],
  ['combine', 'medaglione_b', 'medaglione_k'],
  ['expect', 'item.medaglione'],
  ['use', 'partner', 'talk', { topics: ['c1_adesso'], choices: ['Andiamo a Parigi'] }],

  // ---------- CAPITOLO 2 ----------
  ['scene', 'c2_gare'],
  ['expect', 'chapter==2'],
  ['use', 'cartolina'],
  ['switch', 'kiki'],
  ['use', 'consigne'],
  ['switch', 'beps'],
  ['use', 'uscita'],
  ['scene', 'c2_quai'],
  ['use', 'lucchetto'],
  ['use', 'npc:albert', 'talk', { topics: ['orfeo', 'donna', 'quai', { item: 'moneta' }], choices: ['Christoph'] }],
  ['examine', 'libretto'],
  ['expect', 'item.mappa'],
  ['use', 'verso_marais', null, { topics: ['foto1967', 'studio', 'ada', 'orfeo', 'donna'] }],
  ['scene', 'c2_studio_marchetti'],
  ['expect', 'item.foto1967 && item.negativo'],
  ['use', 'ritratto_ada'],
  ['use', 'ricevuta'],
  ['use', 'gatto'],
  ['use', 'tenda'],
  ['scene', 'c2_camera_oscura'],
  ['use', 'ingranditore', null, { choices: ['Espongo io'] }],
  ['expect', 'flag.retro_1967'],
  ['use', 'provino'],
  ['use', 'uscita'],
  ['use', 'banco'],
  ['expect', 'puzzle.c2_sovrapposizione'],
  ['use', 'uscita'],
  ['use', 'verso_ada', null, { choices: ['mano sulla spalla'] }],
  ['scene', 'c2_appartamento'],
  ['use', 'segreteria'],
  ['use', 'foto_famiglia'],
  ['use', 'diario'],
  ['switch', 'kiki'],
  ['use', 'cappello', 'look'],
  ['use', 'grammofono', null, { choices: ['non ho paura'] }],
  ['switch', 'beps'],
  ['combine', 'mappa', 'medaglione'],

  // ---------- CAPITOLO 3 ----------
  ['scene', 'c3_piazza'],
  ['expect', 'chapter==3'],
  ['use', 'lira_fontana'],
  ['use', 'balcone'],
  ['use', 'npc:caricaturista', 'talk', { topics: ['ritratto', 'donna'] }],
  ['use', 'portone'],
  ['scene', 'c3_biblioteca'],
  ['use', 'npc:ilario', 'talk', { topics: [{ item: 'medaglione' }, 'teodosiana', 'donna', 'xvii', 'notaio'] }],
  ['expect', 'flag.cassetti_ok'],
  ['switch', 'kiki'],
  ['use', 'scala'],
  ['switch', 'beps'],
  ['use', 'catalogo'],
  ['use', 'porta_cassetti'],
  ['scene', 'c3_sala_cassetti'],
  ['item', 'fianco', 'coltellino'],
  ['switch', 'kiki'],
  ['use', 'targa', 'look'],
  ['switch', 'beps'],
  ['use', 'mobile'],
  ['expect', 'puzzle.c3_cassetti && flag.allarme && item.lista17 && item.chiave_ottone'],
  ['use', 'verbale'],
  ['item', 'grata', 'coltellino'],
  ['switch', 'kiki'],
  ['use', 'grata'],
  ['scene', 'c3_passaggio'],
  ['use', 'leva'],
  ['use', 'dittafono'],
  ['switch', 'beps'],
  ['scene', 'c3_sala_cassetti'],
  ['use', 'cancello'],
  ['scene', 'c3_passaggio'],
  ['use', 'scala'],
  ['use', 'scala', null, { choices: ['Abbiamo la chiave'] }],
  ['scene', 'c3_cortile'],
  ['use', 'foglio'],
  ['use', 'verso_osteria'],
  ['scene', 'c3_osteria'],
  ['use', 'foto_muro'],
  ['combine', 'foto1944', 'lista17'],
  ['use', 'partner', 'talk', { topics: ['c3_roma', 'c3_latino', 'c3_federica'] }],
  ['use', 'tavolo', null, { choices: ['Tua nonna e tua bisnonna'] }],

  // ---------- CAPITOLO 4 ----------
  ['scene', 'c4_studio'],
  ['expect', 'chapter==4 && !present.kiki'],
  ['use', 'biglietto'],
  ['use', 'pacco'],
  ['expect', 'flag.sms_ricevuto'],
  ['use', 'porta'],
  ['scene', 'c4_ponte'],
  ['use', 'npc:neri', 'talk', { topics: ['kiki', { item: 'lista17' }, 'nonno', 'banco', 'corridoio'] }],
  ['use', 'vetrina'],
  ['use', 'verso_banca'],
  ['use', 'npc:bellandi', 'talk', { topics: ['cassetta', 'varano'], choices: ['«Euridice»'] }],
  ['expect', 'item.sigillo_b && item.nastro'],
  ['use', 'registro'],
  ['use', 'uscita'],
  ['use', 'banco'],
  ['expect', 'item.sigillo'],
  ['use', 'porta_corridoio'],
  ['scene', 'c4_corridoio'],
  ['use', 'graffito'],
  ['use', 'lira_finestra'],
  ['item', 'porta_orfeo', 'sigillo', { topics: ['perche', 'registro', 'bruciare', 'sigillo', 'nome'], choices: ['Abbracciala'] }],
  ['scene', 'c4_grotta'],
  ['expect', 'flag.kiki_liberata && present.kiki'],
  ['use', 'dittafono'],
  ['use', 'partner', 'talk', { topics: ['c4_scusa'] }],
  ['use', 'uscita'],

  // ---------- CAPITOLO 5 ----------
  ['scene', 'c5_galata'],
  ['use', 'chiosco'],
  ['use', 'simit'],
  ['use', 'verso_bazar'],
  ['use', 'npc:emre', 'talk', { topics: ['te', 'antiquario'] }],
  ['use', 'donna'],
  ['use', 'cassa'],
  ['use', 'verso_antiquario', null, { topics: ['traduttore', 'registro', 'lanterna', 'botola', 'ada', 'donna'] }],
  ['scene', 'c5_antiquario'],
  ['expect', 'item.lanterna && flag.selim_camera'],
  ['use', 'grammofono'],
  ['use', 'foto_1989'],
  ['use', 'gatto'],
  ['use', 'uscita'],
  ['use', 'npc:emre', 'talk', { topics: ['leva', 'donna'] }],
  ['use', 'verso_han'],
  ['scene', 'c5_han'],
  ['use', 'nicchia'],
  ['use', 'scala_tetto', null, { choices: ['Baciala'] }],
  ['scene', 'c5_tetto'],
  ['expect', 'flag.bacio'],
  ['use', 'lettera_comignolo'],
  ['use', 'partner', 'talk', { topics: ['c5_istanbul', 'noi'], choices: ['Quando sarà finito'] }],
  ['use', 'scala'],
  ['item', 'botola', 'piede_porco'],
  ['use', 'botola'],
  ['scene', 'c5_cisterna'],
  ['use', 'lira_medusa'],
  ['use', 'porta_camera'],
  ['scene', 'c5_camera_anelli'],
  ['item', 'anelli', 'medaglione'],

  // ---------- CAPITOLO 6 ----------
  ['scene', 'c6_pont_neuf'],
  ['expect', 'chapter==6 && clue.camera_firenze'],
  ['use', 'panchina', null, { choices: ['non sarà finito'] }],
  ['use', 'verso_atelier', null, { topics: ['istanbul', 'archivio', 'ruolo', 'nastro'] }],
  ['scene', 'c6_atelier'],
  ['use', 'foto_2019'],
  ['use', 'tenda'],
  ['item', 'revox', 'nastro'],
  ['expect', 'flag.nastro_ascoltato'],
  ['use', 'bobine'],
  ['use', 'uscita'],
  ['use', 'uscita'],
  ['use', 'verso_archivio'],
  ['scene', 'c6_archivio'],
  ['use', 'atto'],
  ['use', 'tavolo'],
  ['expect', 'puzzle.c6_cronologia'],
  ['use', 'uscita'],
  ['use', 'partner', 'talk', { topics: ['c6_helene'] }],
  ['use', 'verso_ufficio'],
  ['scene', 'c6_ufficio'],
  ['use', 'lettera_lina'],
  ['use', 'npc:varano6', 'talk', { topics: ['bruno', 'lina', 'verbale', 'camera', 'perche'] }],
  ['expect', 'flag.varano_doubt && flag.varano_c6_fine'],
  ['use', 'uscita'],
  ['scene', 'c6_catacombe'],
  ['use', 'lira_ossa'],
  ['use', 'partner', 'talk', { topics: ['c6_varano'] }],
  ['use', 'uscita'],

  // ---------- CAPITOLO 7 ----------
  ['scene', 'c7_cantiere'],
  ['expect', 'chapter==7'],
  ['use', 'partner', 'talk', { topics: ['c7_paura'] }],
  ['use', 'gradini'],
  ['use', 'gradini'],
  ['use', 'gradini'],
  ['scene', 'c7_galleria'],
  ['use', 'lira_volta'],
  ['expect', 'flag.knows_18'],
  ['use', 'ruota'],
  ['use', 'nicchia_voce'],
  ['use', 'iscrizione', 'look'],
  ['use', 'arco'],
  ['scene', 'c7_camera'],
  ['use', 'foto_originale'],
  ['use', 'iscrizione', 'look'],
  ['item', 'incavo', 'sigillo'],
  ['switch', 'kiki'],
  ['item', 'grammofono', 'nastro'],
  ['use', 'ruota_nomi'],
  ['use', 'leva'],
  ['switch', 'beps'],
  ['item', 'serratura', 'chiave_ottone'],
  ['expect', 'flag.meccanismo_aperto && flag.final_perfect && flag.eighteenth_written'],
  ['use', 'registro_scrigno'],
  ['scene', 'c7_alba'],
  ['use', 'donna_ponte'],
  ['checkpoint', 'pre_ending'],
  ['use', 'npc:varano7', 'talk', { topics: ['luce', 'custodi', 'cenere', 'noi'] }]
];

// MINIMAL: solo i passi obbligatori, scelte fredde o sbagliate. Deve arrivare in fondo
// (nessun dead-end) e lasciare disponibile solo Cenere.
export const MINIMAL = [
  ['use', 'computer', null, { choices: ['foto'] }],
  ['use', 'macchinetta'],
  ['use', 'porta'],
  ['use', 'verso_cantiere'],
  ['use', 'npc:sandro', 'talk', { topics: ['caffe_dato'] }],
  ['item', 'armadio', 'coltellino'],
  ['use', 'crepa'],
  ['item', 'tavolo', 'frammenti'],
  ['use', 'uscita'],
  ['use', 'porta_archivio'],
  ['use', 'npc:archivista', 'talk', { topics: [{ item: 'foto1944' }] }],
  ['use', 'schedario', null, { choices: ['Chi è lei', 'Perché dovrei'] }],
  ['use', 'porta_deposito'],
  ['use', 'ripiano'],
  ['switch', 'kiki'],
  ['use', 'quadro'],
  ['switch', 'beps'],
  ['use', 'uscita'],
  ['use', 'uscita'],
  ['use', 'porta_caffe'],
  ['item', 'laptop', 'usb', { choices: ['terzo gradino'] }],
  ['use', 'partner', 'talk', { topics: ['c1_medaglione'], choices: ['mercatino'] }],
  ['combine', 'medaglione_k', 'medaglione_b'],
  ['use', 'partner', 'talk', { topics: ['c1_adesso'], choices: ['Vado io'] }],
  ['scene', 'c2_gare'],
  ['use', 'uscita'],
  ['use', 'verso_marais', null, { topics: ['foto1967'] }],
  ['use', 'tenda'],
  ['use', 'ingranditore', null, { choices: ['tutorial'] }],
  ['use', 'uscita'],
  ['use', 'banco'],
  ['use', 'uscita'],
  ['use', 'npc:albert', 'talk', { topics: ['orfeo', 'orfeo'], choices: ['Offenbach', 'Christoph'] }],
  ['examine', 'libretto'],
  ['combine', 'medaglione', 'mappa'],
  ['scene', 'c3_piazza'],
  ['use', 'portone'],
  ['use', 'npc:ilario', 'talk', { topics: [{ item: 'medaglione' }] }],
  ['use', 'porta_cassetti'],
  ['item', 'fianco', 'coltellino'],
  ['switch', 'kiki'],
  ['use', 'targa', 'look'],
  ['use', 'mobile'],
  ['use', 'grata'],
  ['switch', 'beps'],
  ['item', 'grata', 'coltellino'],
  ['switch', 'kiki'],
  ['use', 'grata'],
  ['use', 'leva'],
  ['switch', 'beps'],
  ['use', 'cancello'],
  ['use', 'scala'],
  ['use', 'scala', null, { choices: ['carbonara'] }],
  ['use', 'verso_osteria'],
  ['use', 'tavolo', null, { choices: ['Tutto torna'] }],
  ['scene', 'c4_studio'],
  ['use', 'porta'],
  ['use', 'pacco'],
  ['use', 'porta'],
  ['use', 'npc:neri', 'talk', { topics: [{ item: 'lista17' }, 'banco', 'corridoio'] }],
  ['use', 'verso_banca'],
  ['use', 'npc:bellandi', 'talk', { topics: ['cassetta', 'cassetta'], choices: ['«Orfeo»', '«Euridice»'] }],
  ['use', 'uscita'],
  ['use', 'banco'],
  ['use', 'porta_corridoio'],
  ['item', 'porta_orfeo', 'sigillo', { topics: [], choices: ['cronometro'] }],
  ['use', 'uscita'],
  ['scene', 'c5_galata'],
  ['use', 'verso_bazar'],
  ['use', 'verso_antiquario', null, { topics: ['traduttore', 'registro', 'lanterna'] }],
  ['use', 'uscita'],
  ['use', 'npc:emre', 'talk', { topics: ['leva'] }],
  ['use', 'verso_han'],
  ['item', 'botola', 'piede_porco'],
  ['use', 'botola'],
  ['use', 'porta_camera'],
  ['item', 'anelli', 'medaglione'],
  ['expect', 'puzzle.c5_anelli && !flag.tetto_scena'],
  ['use', 'uscita'],
  ['use', 'uscita'],
  ['scene', 'c5_han'],
  ['use', 'scala_tetto', null, { choices: ['malta'] }],
  ['scene', 'c6_pont_neuf'],
  ['use', 'verso_atelier', null, { topics: [] }],
  ['use', 'tenda'],
  ['item', 'revox', 'nastro'],
  ['use', 'uscita'],
  ['use', 'uscita'],
  ['use', 'verso_archivio'],
  ['use', 'tavolo'],
  ['use', 'uscita'],
  ['use', 'verso_ufficio'],
  ['use', 'npc:varano6', 'talk', { topics: [] }],
  ['use', 'uscita'],
  ['use', 'uscita'],
  ['scene', 'c7_cantiere'],
  ['use', 'gradini'],
  ['use', 'gradini'],
  ['use', 'gradini'],
  ['use', 'ruota'],
  ['use', 'arco'],
  ['item', 'serratura', 'chiave_ottone'],
  ['item', 'incavo', 'sigillo'],
  ['switch', 'kiki'],
  ['use', 'ruota_nomi'],
  ['item', 'grammofono', 'nastro'],
  ['use', 'ruota_nomi'],
  ['use', 'leva'],
  ['switch', 'beps'],
  ['item', 'serratura', 'chiave_ottone'],
  ['expect', 'flag.meccanismo_aperto && !flag.final_perfect'],
  ['use', 'registro_scrigno'],
  ['scene', 'c7_alba'],
  ['checkpoint', 'pre_ending'],
  ['use', 'npc:varano7', 'talk', { topics: [] }]
];
